### ISSUE TITLE
Peer to Peer Code Review (27th January)

### ISSUE THREAD

**Issue by Thoth1111** [tonnytech/Todo-List-v2#4]
Great progress so far but there are quite a few changes you need to make to improve the functionality:
- Your Live Demo link needs to be updated. You should run npm build so that the live demo is up to date
- The README requires some changes. The Microverse logo should be excluded, and the braces removed from the headings. Same goes for the instructions and comments.
- It's a good idea to create more than one module to make the project a little easy to understand.
- in webpack config if you want to really use the fonts use file-loader [webpack file-loader](https://chriscourses.com/blog/loading-fonts-webpack
-Ticking a task as completed updates the wrong task in the local storage.

Happy coding 😄

**Comment by tonnytech** [comment]
Thanks a lot for the review, I'm working the changes. 😊👀👌
